# Generated by Django 4.0.4 on 2022-07-02 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('serial_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('manufacturer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AirPortInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('icao', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('subd', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('elevation', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('tz', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArrivalInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('estemated_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airport_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_manager_api.airportinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DepartureInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('estemated_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airport_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_manager_api.airportinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_manager_api.arrivalinfo')),
                ('departure_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_manager_api.departureinfo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
