# Generated by Django 4.0.4 on 2022-07-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_manager_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_manager_api.aircraft'),
        ),
        migrations.AlterField(
            model_name='airportinfo',
            name='icao',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
